name: Publish to GitHub Packages
#
on:
  workflow_run:
    workflows: ["Java Leaflet Build"]
    types:
      - completed
#    branches:
#     - 'dev/**'
#
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Deploy to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_PACKAGE_TOKEN }}
        run: mvn deploy
