name: Publish to GitHub Packages on Release Branch

on:
  workflow_run:
    workflow: "Java Leaflet Build"
    type: completed
    branches:
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Deploy to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_PACKAGE_TOKEN }}
        run: mvn deploy
