name: Java Leaflet Build
#
on: [ push ]
#
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This step uses the `actions/checkout` action to download a copy of your repository on the runner.
      - uses: actions/checkout@v3
      # This step uses the `actions/setup-java` action to configure the Eclipse Temurin (Java) 17 JDK by Eclipse Adoptium.
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

  deploy:
    needs: [ "build" ]
    if: contains(github.ref_name, 'dev/')
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Deploy to GitHub Packages
        env:
          GITHUB_USERNAME: makbn
          GITHUB_ACTOR: makbn
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -e --settings settings.xml deploy

